# Programming Assignment 8

Submitted By : Abhishek Kumar Singh

#### 1. Write a Python Program to Add Two Matrices?

In [1]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = [[X[i][j] + Y[i][j]  for j in range
(len(X[0]))] for i in range(len(X))]
  
for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


#### 2. Write a Python Program to Multiply Two Matrices?

In [5]:
import numpy as np

In [9]:
mat1 = ([1,2,3],[4,5,6],[1,3,5])
mat2 = ([2,4,6],[1,3,5],[5,7,9])

print(np.dot(mat1,mat2))

[[ 19  31  43]
 [ 43  73 103]
 [ 30  48  66]]


#### 3. Write a Python Program to Transpose a Matrix?

In [12]:
mat = ([1,2,3],[2,4,6],[2,3,5])
np.transpose(mat)

array([[1, 2, 2],
       [2, 4, 3],
       [3, 6, 5]])

#### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [15]:
words = ['California','Ice Land','Maldives','Australia','Newzealand']
print(np.sort(words))

['Australia' 'California' 'Ice Land' 'Maldives' 'Newzealand']


#### 5. Write a Python Program to Remove Punctuation From a String?

In [22]:
import string
text = "Hii!!! M[y] Name is ?"
new_text = text.translate(str.maketrans("","",string.punctuation))


print(new_text)

Hii My Name is 


In [26]:
import string

punctuations = string.punctuation
my_str = "Hello!!!, he said ---and went."


str_pun = input("Enter a string: ")


no_punct = ""
for char in str_pun:
   if char not in punctuations:
       no_punct = no_punct + char

print(no_punct)

Enter a string: Hello!! M[?y name is Abhishek
Hello My name is Abhishek
